# Do not use tabs in this file!
encoding: utf-8

author: Alex Wood

# Change this if we ever need the site to reside in a sub-directory
baseurl: ''

assets:
  prefix: "/assets"

exclude:
  - 'vendor'
  - 'Gemfile*'
  - 'README.md'
  - 'config.ru'

paginate: 8
paginate_path: /news/page:num

sass:
  sass_dir: _sass
  style: :compressed

kramdown:
  # Use GitHub flavor markdown
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-assets
